#
###################################
# Site wide configuration
####################################
#
title: Raphael Saldanha
email: rfsaldanha@gmail.com
description: Geógrafo e Cientista de Dados em Saúde
url: https://rfsaldanha.github.io # the base hostname & protocol for your site
keywords: ["Geografia", "Saúde", "Visualização"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Sao_Paulo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Raphael Saldanha
  avatar: leonids-logo.png
  job: "Saúde Pública e Visualização de Dados"
  bio: "Geógrafo da Saúde, apaixonado por visualização de dados e Data Science."
  email: rfsaldanha@gmail.com
  disqus-shortname: rfsaldanha
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rfsaldanha #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
